// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// P_2PL_cpp
NumericVector P_2PL_cpp(const NumericMatrix& theta, const NumericVector& a, double b);
RcppExport SEXP _lblvm_P_2PL_cpp(SEXP thetaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(P_2PL_cpp(theta, a, b));
    return rcpp_result_gen;
END_RCPP
}
// P_DRM_cpp
List P_DRM_cpp(const NumericMatrix& theta, const NumericVector& a, double b, double nu, const NumericVector& cut_score, bool return_mu);
RcppExport SEXP _lblvm_P_DRM_cpp(SEXP thetaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nuSEXP, SEXP cut_scoreSEXP, SEXP return_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cut_score(cut_scoreSEXP);
    Rcpp::traits::input_parameter< bool >::type return_mu(return_muSEXP);
    rcpp_result_gen = Rcpp::wrap(P_DRM_cpp(theta, a, b, nu, cut_score, return_mu));
    return rcpp_result_gen;
END_RCPP
}
// llik_cpp
NumericMatrix llik_cpp(const IntegerVector& data, const NumericMatrix& theta, const NumericVector& item, const NumericVector& cut_score);
RcppExport SEXP _lblvm_llik_cpp(SEXP dataSEXP, SEXP thetaSEXP, SEXP itemSEXP, SEXP cut_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type item(itemSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cut_score(cut_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(llik_cpp(data, theta, item, cut_score));
    return rcpp_result_gen;
END_RCPP
}
// llik_ratio_mhrm
NumericVector llik_ratio_mhrm(const NumericMatrix& data, const NumericMatrix& theta_c, const NumericMatrix& theta_p, const NumericMatrix& item, const List& cut_score, const NumericMatrix& Sigma_inv);
RcppExport SEXP _lblvm_llik_ratio_mhrm(SEXP dataSEXP, SEXP theta_cSEXP, SEXP theta_pSEXP, SEXP itemSEXP, SEXP cut_scoreSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta_c(theta_cSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta_p(theta_pSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type item(itemSEXP);
    Rcpp::traits::input_parameter< const List& >::type cut_score(cut_scoreSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(llik_ratio_mhrm(data, theta_c, theta_p, item, cut_score, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// llik_mhrm
double llik_mhrm(const NumericMatrix& data, const NumericMatrix& theta_c, const NumericMatrix& item, const List& cut_score, const NumericMatrix& Sigma_inv);
RcppExport SEXP _lblvm_llik_mhrm(SEXP dataSEXP, SEXP theta_cSEXP, SEXP itemSEXP, SEXP cut_scoreSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta_c(theta_cSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type item(itemSEXP);
    Rcpp::traits::input_parameter< const List& >::type cut_score(cut_scoreSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(llik_mhrm(data, theta_c, item, cut_score, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// Estep_cpp
List Estep_cpp(IntegerMatrix data, NumericMatrix item, NumericMatrix grid, NumericVector prior, List cut_score);
RcppExport SEXP _lblvm_Estep_cpp(SEXP dataSEXP, SEXP itemSEXP, SEXP gridSEXP, SEXP priorSEXP, SEXP cut_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type item(itemSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type cut_score(cut_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(Estep_cpp(data, item, grid, prior, cut_score));
    return rcpp_result_gen;
END_RCPP
}
// compute_pmat
NumericMatrix compute_pmat(const NumericVector& beta_grid, const NumericVector& mu, double nu);
RcppExport SEXP _lblvm_compute_pmat(SEXP beta_gridSEXP, SEXP muSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type beta_grid(beta_gridSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pmat(beta_grid, mu, nu));
    return rcpp_result_gen;
END_RCPP
}
// compute_l1_cpp
List compute_l1_cpp(const arma::mat& grid, double nu, const arma::vec& mu, const arma::vec& beta_grid, int ncats, const arma::ivec& ind_cat);
RcppExport SEXP _lblvm_compute_l1_cpp(SEXP gridSEXP, SEXP nuSEXP, SEXP muSEXP, SEXP beta_gridSEXP, SEXP ncatsSEXP, SEXP ind_catSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_grid(beta_gridSEXP);
    Rcpp::traits::input_parameter< int >::type ncats(ncatsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ind_cat(ind_catSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_l1_cpp(grid, nu, mu, beta_grid, ncats, ind_cat));
    return rcpp_result_gen;
END_RCPP
}
// Grad_IM_cpp
List Grad_IM_cpp(List l1s, const arma::mat& e_resp, const arma::mat& p0, const arma::vec& f, Nullable<arma::mat> posterior, Nullable<arma::ivec> response, bool calculate);
RcppExport SEXP _lblvm_Grad_IM_cpp(SEXP l1sSEXP, SEXP e_respSEXP, SEXP p0SEXP, SEXP fSEXP, SEXP posteriorSEXP, SEXP responseSEXP, SEXP calculateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l1s(l1sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e_resp(e_respSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< Nullable<arma::mat> >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< Nullable<arma::ivec> >::type response(responseSEXP);
    Rcpp::traits::input_parameter< bool >::type calculate(calculateSEXP);
    rcpp_result_gen = Rcpp::wrap(Grad_IM_cpp(l1s, e_resp, p0, f, posterior, response, calculate));
    return rcpp_result_gen;
END_RCPP
}
// Estep_Cont_cpp
List Estep_Cont_cpp(const NumericMatrix& data, const NumericMatrix& item, const NumericMatrix& grid, const NumericVector& prior);
RcppExport SEXP _lblvm_Estep_Cont_cpp(SEXP dataSEXP, SEXP itemSEXP, SEXP gridSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type item(itemSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(Estep_Cont_cpp(data, item, grid, prior));
    return rcpp_result_gen;
END_RCPP
}
// cont_L1L2_cpp
List cont_L1L2_cpp(const arma::vec& item, const arma::mat& grid, const arma::vec& data, const arma::mat& Pk, bool calculate_m);
RcppExport SEXP _lblvm_cont_L1L2_cpp(SEXP itemSEXP, SEXP gridSEXP, SEXP dataSEXP, SEXP PkSEXP, SEXP calculate_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type item(itemSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Pk(PkSEXP);
    Rcpp::traits::input_parameter< bool >::type calculate_m(calculate_mSEXP);
    rcpp_result_gen = Rcpp::wrap(cont_L1L2_cpp(item, grid, data, Pk, calculate_m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lblvm_P_2PL_cpp", (DL_FUNC) &_lblvm_P_2PL_cpp, 3},
    {"_lblvm_P_DRM_cpp", (DL_FUNC) &_lblvm_P_DRM_cpp, 6},
    {"_lblvm_llik_cpp", (DL_FUNC) &_lblvm_llik_cpp, 4},
    {"_lblvm_llik_ratio_mhrm", (DL_FUNC) &_lblvm_llik_ratio_mhrm, 6},
    {"_lblvm_llik_mhrm", (DL_FUNC) &_lblvm_llik_mhrm, 5},
    {"_lblvm_Estep_cpp", (DL_FUNC) &_lblvm_Estep_cpp, 5},
    {"_lblvm_compute_pmat", (DL_FUNC) &_lblvm_compute_pmat, 3},
    {"_lblvm_compute_l1_cpp", (DL_FUNC) &_lblvm_compute_l1_cpp, 6},
    {"_lblvm_Grad_IM_cpp", (DL_FUNC) &_lblvm_Grad_IM_cpp, 7},
    {"_lblvm_Estep_Cont_cpp", (DL_FUNC) &_lblvm_Estep_Cont_cpp, 4},
    {"_lblvm_cont_L1L2_cpp", (DL_FUNC) &_lblvm_cont_L1L2_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_lblvm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
