# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

P_2PL_cpp <- function(theta, a, b) {
    .Call(`_lblvm_P_2PL_cpp`, theta, a, b)
}

P_DRM_cpp <- function(theta, a, b, nu, cut_score, return_mu = FALSE) {
    .Call(`_lblvm_P_DRM_cpp`, theta, a, b, nu, cut_score, return_mu)
}

llik_cpp <- function(data, theta, item, cut_score) {
    .Call(`_lblvm_llik_cpp`, data, theta, item, cut_score)
}

llik_ratio_mhrm <- function(data, theta_c, theta_p, item, cut_score, Sigma_inv) {
    .Call(`_lblvm_llik_ratio_mhrm`, data, theta_c, theta_p, item, cut_score, Sigma_inv)
}

llik_mhrm <- function(data, theta_c, item, cut_score, Sigma_inv) {
    .Call(`_lblvm_llik_mhrm`, data, theta_c, item, cut_score, Sigma_inv)
}

Estep_cpp <- function(data, item, grid, prior, cut_score) {
    .Call(`_lblvm_Estep_cpp`, data, item, grid, prior, cut_score)
}

compute_pmat <- function(beta_grid, mu, nu) {
    .Call(`_lblvm_compute_pmat`, beta_grid, mu, nu)
}

compute_l1_cpp <- function(grid, nu, mu, beta_grid, ncats, ind_cat) {
    .Call(`_lblvm_compute_l1_cpp`, grid, nu, mu, beta_grid, ncats, ind_cat)
}

Grad_IM_cpp <- function(l1s, e_resp, p0, f, posterior = NULL, response = NULL, calculate = FALSE) {
    .Call(`_lblvm_Grad_IM_cpp`, l1s, e_resp, p0, f, posterior, response, calculate)
}

Estep_Cont_cpp <- function(data, item, grid, prior) {
    .Call(`_lblvm_Estep_Cont_cpp`, data, item, grid, prior)
}

cont_L1L2_cpp <- function(item, grid, data, Pk, calculate_m = FALSE) {
    .Call(`_lblvm_cont_L1L2_cpp`, item, grid, data, Pk, calculate_m)
}

